name: Flyplugin
version: '${project.version}'
main: de.denis.flyplugin.Flyplugin
authors: [ Denis, Altintas ]
description: Dieses Plugin lässt dich fliegen!
commands:
  fly:
    description: Dieses Plugin lässt dich fliegen!