name: Flyplugin
version: '${project.version}'
main: de.denis.flyplugin.Flyplugin
authors: [ Denis, Altintas ]
description: Dieses Plugin lässt dich fliegen!
commands:
  fly:
    description: Dieser Befehl laesst dich fliegen!
  flyspeed:
    description: Dieser Befehl beeinflusst deine Fluggeschwindigkeit!
